# Generated by Django 5.0.3 on 2024-04-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_permission', models.IntegerField(default=0)),
            ],
        ),
    ]
