# Generated by Django 4.2.8 on 2024-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_permission', models.IntegerField(default=0)),
            ],
        ),
    ]
