# Generated by Django 5.0.6 on 2024-05-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('device_idx', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='none', max_length=30, unique=True)),
                ('device_profile_name', models.CharField(default='none', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('profile_idx', models.AutoField(primary_key=True, serialize=False)),
                ('profile_count', models.IntegerField(default='-1')),
                ('device_name', models.CharField(default='none', max_length=100)),
                ('project_name', models.CharField(default='none', max_length=100)),
                ('scene_name', models.CharField(default='none', max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField(default=0.0)),
                ('min_fps', models.FloatField(default=0.0)),
                ('avg_fps', models.FloatField(default=0.0)),
                ('max_fps', models.FloatField(default=0.0)),
                ('set_pass_call', models.FloatField(default=0.0)),
                ('draw_call', models.FloatField(default=0.0)),
                ('tris', models.FloatField(default=0.0)),
                ('vertices', models.FloatField(default=0.0)),
                ('total_memory', models.FloatField(default=0.0)),
                ('system_memory', models.FloatField(default=0.0)),
                ('texture_memory', models.FloatField(default=0.0)),
                ('mesh_memory', models.FloatField(default=0.0)),
                ('user_nickname', models.CharField(default='none', max_length=100)),
                ('build_version', models.CharField(default='none', max_length=100)),
                ('system_os', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLiveData',
            fields=[
                ('profile_live_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_count', models.IntegerField(default='-1')),
                ('device_name', models.CharField(default='none', max_length=100)),
                ('project_name', models.CharField(default='none', max_length=100)),
                ('scene_name', models.CharField(default='none', max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField(default=0.0)),
                ('min_fps', models.FloatField(default=0.0)),
                ('avg_fps', models.FloatField(default=0.0)),
                ('max_fps', models.FloatField(default=0.0)),
                ('set_pass_call', models.FloatField(default=0.0)),
                ('draw_call', models.FloatField(default=0.0)),
                ('tris', models.FloatField(default=0.0)),
                ('vertices', models.FloatField(default=0.0)),
                ('total_memory', models.FloatField(default=0.0)),
                ('system_memory', models.FloatField(default=0.0)),
                ('texture_memory', models.FloatField(default=0.0)),
                ('mesh_memory', models.FloatField(default=0.0)),
                ('user_nickname', models.CharField(default='none', max_length=100)),
                ('build_version', models.CharField(default='none', max_length=100)),
                ('system_os', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRecordInfo',
            fields=[
                ('profile_record_info_idx', models.AutoField(primary_key=True, serialize=False)),
                ('profile_record_title', models.CharField(default='none', max_length=100)),
                ('profile_record_contents', models.CharField(default='none', max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(default='none', max_length=100)),
                ('profile_record_start_idx', models.IntegerField(default='-1')),
                ('profile_record_end_idx', models.IntegerField(default='-1')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRecord',
            fields=[
                ('profile_record_idx', models.AutoField(primary_key=True, serialize=False)),
                ('profile_count', models.IntegerField(default='-1')),
                ('device_name', models.CharField(default='none', max_length=100)),
                ('project_name', models.CharField(default='none', max_length=100)),
                ('scene_name', models.CharField(default='none', max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField(default=0.0)),
                ('min_fps', models.FloatField(default=0.0)),
                ('avg_fps', models.FloatField(default=0.0)),
                ('max_fps', models.FloatField(default=0.0)),
                ('set_pass_call', models.FloatField(default=0.0)),
                ('draw_call', models.FloatField(default=0.0)),
                ('tris', models.FloatField(default=0.0)),
                ('vertices', models.FloatField(default=0.0)),
                ('total_memory', models.FloatField(default=0.0)),
                ('system_memory', models.FloatField(default=0.0)),
                ('texture_memory', models.FloatField(default=0.0)),
                ('mesh_memory', models.FloatField(default=0.0)),
                ('user_nickname', models.CharField(default='none', max_length=100)),
                ('build_version', models.CharField(default='none', max_length=100)),
                ('system_os', models.CharField(default='none', max_length=100)),
                ('profile_record_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_infos', to='unityprofile.profilerecordinfo')),
            ],
        ),
    ]
