# Generated by Django 4.2.8 on 2024-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLiveData',
            fields=[
                ('profile_live_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_count', models.IntegerField(default='-1')),
                ('device_name', models.CharField(default='none', max_length=100)),
                ('project_name', models.CharField(default='none', max_length=100)),
                ('scene_name', models.CharField(default='none', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField(default=0.0)),
                ('min_fps', models.FloatField(default=0.0)),
                ('avg_fps', models.FloatField(default=0.0)),
                ('max_fps', models.FloatField(default=0.0)),
                ('set_pass_call', models.FloatField(default=0.0)),
                ('draw_call', models.FloatField(default=0.0)),
                ('tris', models.FloatField(default=0.0)),
                ('vertices', models.FloatField(default=0.0)),
                ('total_memory', models.FloatField(default=0.0)),
                ('system_memory', models.FloatField(default=0.0)),
                ('texture_memory', models.FloatField(default=0.0)),
                ('mesh_memory', models.FloatField(default=0.0)),
                ('user_nickname', models.CharField(default='none', max_length=100)),
                ('build_version', models.CharField(default='none', max_length=100)),
                ('system_os', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
