# Generated by Django 4.2.8 on 2024-04-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityprofile', '0002_profilelivedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerecordinfo',
            name='user_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
