# Generated by Django 4.2.8 on 2024-04-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo2',
            fields=[
                ('device_idx', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='none', max_length=30, unique=True)),
                ('device_profile_name', models.CharField(default='none', max_length=30)),
            ],
        ),
    ]
